WebGridSample/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebGridSample.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebGridSample/Controllers/WebGridController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGridSample.Models;

namespace WebGridSample.Controllers
{
    public class WebGrid_Sample1Controller : Controller
    {
        // GET: WebGrid
        public ActionResult Show1(StudentVm oSVm)
        {
            StudentVm SVm = new StudentVm(); //.GetStudents(oSVm);
            SVm.Students= SVm.GetStudents(oSVm);
            return View(SVm);
        }
    }

    
}

WebGridSample/Controllers/WebGrid_Sample2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGridSample.Models;

namespace WebGridSample.Controllers
{
    public class WebGrid_Sample2Controller : Controller
    {
        // GET: WebGrid_Sample2
        public ActionResult Show2(StudentVm oSVm)
        {
            StudentVm SVm = new StudentVm(); 
            SVm.Students = SVm.GetStudents(oSVm);
            return View(SVm);
        }

    }
}

WebGridSample/Controllers/WebGrid_Sample3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebGridSample.Models;
using DataLayer.Repository;

namespace WebGridSample.Controllers
{
    public class WebGrid_Sample3Controller : Controller
    {
        private StudentRepository _data;

        public WebGrid_Sample3Controller()
        {
            _data = new StudentRepository(System.Configuration.ConfigurationManager.ConnectionStrings["StudentDBContext"].ConnectionString);
        }

        // GET: WebGrid_Sample3
        public ActionResult Show3(StudentVm oSVm)
        {
            System.Threading.Thread.Sleep(1000); // just simulate delay of one second
            StudentVm SVm = new StudentVm();
            SVm.Students = SVm.GetStudents(oSVm);
            return View(SVm);
        }

        public ActionResult List(StudentVm oSVm)
        {
            System.Threading.Thread.Sleep(1000); // just simulate delay of one second
            StudentVm SVm = new StudentVm();
            SVm.SetUpParams(oSVm);
            SVm.StudentList = _data.GetStudents(SVm.StartIndex, SVm.EndIndex, SVm.sort, oSVm.sortdir);
            SVm.RowCount = _data.DataCounter;
            return View("Show3",SVm);
        }
    }
}

WebGridSample/Views/Default/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<style>
footer {
    position: absolute;
    bottom: 0;
    width: 70%;
}

    #Menu {
    position:absolute;
    top: 50%;
    left: 50%;
    width:30em;
    height:18em;
    margin-top: -9em; /*set to a negative number 1/2 of your height*/
    margin-left: -15em; /*set to a negative number 1/2 of your width*/
    border: 1px solid #ccc;
    background-color: #f3f3f3;
}
    #Menu
    {
        width: auto;
        height: auto;
    }

    #Menu ul {
        list-style-type: none;
        margin: 0;
        padding: 0;
        width: 250px;
        background-color: #f1f1f1;
    }

    #Menu li a {
        display: block;
        color: #000;
        padding: 8px 0 8px 16px;
        text-decoration: none;
    }

        #Menu li a.active {
            background-color: #4CAF50;
            color: white;
        }

        #Menu li a:hover:not(.active) {
            background-color: #555;
            color: white;
        }
</style>

<div id="Menu">
    <ul>
        <li><a class="active" href='@Url.Action("Index", "Default")'>Main Page</a></li>
        <li><a href='@Url.Action("Show1", "WebGrid_Sample1")'>WebGrid Sample in main view</a></li>
        <li><a href='@Url.Action("Show2", "WebGrid_Sample2")'>WebGrid Sample with partial view</a></li>
        <li><a href='@Url.Action("Show3", "WebGrid_Sample3")'>WebGrid With Styled Pager</a></li>
    </ul>
</div>